services:
  file_linters:
    image: file_linters:latest
    build:
      context: .
      target: file_linters
    volumes:
      - ".:/app"
  main_build_service:
    image: main_build_service:latest
    build:
      context: .
      target: main_build_service
    volumes:
      - '.:/app'
