name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment that should be used for the Workflow (staging or production)
        required: true
        type: string

jobs:
  deployment_manager:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/78688761467/locations/global/workloadIdentityPools/github-actions/providers/weather-streamer'
        service_account: '"github-actions@weather-streamer.iam.gserviceaccount.com"'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'