name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment that should be used for the Workflow (staging or production)
        required: true
        type: string

env:
  GCP_CREDENTIALS: {{ secrets.GCP_CREDENTIALS }}}

jobs:
  deployment-manager:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'