name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment that should be used for the Workflow (staging or production)
        required: true
        type: string

env:
    GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
    GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/78688761467/locations/global/workloadIdentityPools/github-actions/providers/weather-streamer'
        service_account: '"github-actions@weather-streamer.iam.gserviceaccount.com"'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'