name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_all:
    uses: ./.github/workflows/deploy_base.yml
    with:
      environment: production
    secrets: inherit
