name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment that should be used for the Workflow (staging or production)
        required: true
        type: string
  workflow_dispatch:

jobs:
  deployment_manager:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Run Pub/Sub Deployment in Deployment Manager
        run: gcloud deployment-manager deployments update pub-sub-topic --config infrastructure/pub-sub-topic.yml --project ${{ secrets.GCP_PROJECT_ID }}
